# Generated by Django 3.1.2 on 2020-10-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
