# Generated by Django 3.1.2 on 2020-10-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20201006_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
